---
- name: Ensure if GPG package exists
  apt:
    update_cache: yes
    pkg:
      - gpg

- name: Add Proxmox VE repo key
  get_url:
    url: "{{ proxmox_gpg_url }}"
    dest: /usr/share/keyrings/{{ proxmox_gpg_url.split("/")[-1].split(".")[0] }}-archive-keyring.gpg
    checksum: "{{ proxmox_gpg_checksum }}"
  register: key

- name: Adapt sources.list
  apt_repository:
    filename: pve-install-repo.list
    repo: "deb [signed-by={{ key.dest }}] {{ proxmox_apt_repository }}"
    state: present

- name: Install Proxmox packages
  apt:
    pkg:
      - open-iscsi
      - postfix
      - proxmox-ve
  register: proxmox_installation

- name: Proxmox post-install procedures
  block:
    - name: Reboot the machine
      reboot:
        reboot_timeout: 5

    - name: Remove os-prober package
      apt:
        pkg: os-prober
        state: absent
      retries: 5
      delay: 3
      register: result
      until: result is not failed

    - name: Remove pve subscription packages
      file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: Ensure apt is alright
      apt:
        update_cache: yes
  when: proxmox_installation.changed
