---
# tasks file for fajfer-proxmox

- name: Adapt sources.list
  shell: |
    echo "deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list
    
- name:  Add Proxmox VE repo key as as root & verify key
  get_url: 
    url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
    checksum: "sha512:7fb03ec8a1675723d2853b84aa4fdb49a46a3bb72b9951361488bfd19b29aab0a789a4f8c7406e71a69aabbc727c936d3549731c4659ffa1a08f44db8fdcebfa"

- name: Update and upgrade apt packages
  become: true 
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Proxmox
  apt: 
   name: "{{ item }}"
   state: present
  loop: 
  - proxmox-ve
  - postfix
  - open-iscsi

- name: Reboot the machine
  reboot:
  
- name: Remove os-prober package
  apt:
    name: "{{ item }}"
    state: present
  loop: 
    - os-prober


